[package]
name = "splendid-flows"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
base64 = "0.21.3"
flowsnet-platform-sdk = "0.1.5"
http_req_wasi = "0.11.1"
log = "0.4.20"
serde = "1.0.188"
serde_json = "1.0"
store-flows = "0.3.1"
tokio_wasi = { version = "1.25.0", features = ["rt", "macros"] }
webhook-flows = "0.4.0"
